export {
  PrismaClient,
  Role,
  UserStatus,
  Genre,
  DayOfWeek,
  SessionStatus,
  AttendanceStatus,
  ReportStatus,
  RescheduleStatus,
  PaymentStatus,
  NotificationChannel,
  NotificationType,
  NotificationStatus,
} from "@prisma/client";
export type {
  Tenant,
  User,
  Student,
  StudentParent,
  Course,
  StudentCourse,
  LessonSlot,
  LessonSession,
  Attendance,
  LessonNote,
  MonthlySummary,
  RescheduleRequest,
  Payment,
  Notification,
} from "@prisma/client";
